In [46]:
import numpy as np
import pandas as pd
import pickle
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler

In [47]:
df = pd.read_csv('data/processed_data.csv')

In [48]:
df.shape

(7032, 20)

In [49]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes


#Separando as variáveis categoricas e variáveis numéricas

In [50]:
X = df.drop('Churn', axis=1)
y = df['Churn']

#Aplicando o OneHotEncoder para as variáveis categoricas e o LabelEncoder para a classe

In [51]:
index_categorical_features = [0,2,3,5,6,7,8,9,10,11,12,13,14,15,16]
OneHotEncoder_features = ColumnTransformer(transformers=[('OneHotEncoder', OneHotEncoder(), index_categorical_features)], remainder='passthrough')
LabelEncoder_classe = LabelEncoder()
X = OneHotEncoder_features.fit_transform(X)
y = LabelEncoder_classe.fit_transform(y)

In [52]:
X,X.shape

(array([[1.0000e+00, 0.0000e+00, 0.0000e+00, ..., 1.0000e+00, 2.9850e+01,
         2.9850e+01],
        [0.0000e+00, 1.0000e+00, 1.0000e+00, ..., 3.4000e+01, 5.6950e+01,
         1.8895e+03],
        [0.0000e+00, 1.0000e+00, 1.0000e+00, ..., 2.0000e+00, 5.3850e+01,
         1.0815e+02],
        ...,
        [1.0000e+00, 0.0000e+00, 0.0000e+00, ..., 1.1000e+01, 2.9600e+01,
         3.4645e+02],
        [0.0000e+00, 1.0000e+00, 0.0000e+00, ..., 4.0000e+00, 7.4400e+01,
         3.0660e+02],
        [0.0000e+00, 1.0000e+00, 1.0000e+00, ..., 6.6000e+01, 1.0565e+02,
         6.8445e+03]], shape=(7032, 45)),
 (7032, 45))

In [53]:
y,y.shape

(array([0, 0, 1, ..., 0, 1, 0], shape=(7032,)), (7032,))

#Padronizando variáveis categoricas

In [54]:
scaler_df = StandardScaler()
X = scaler_df.fit_transform(X)
X

array([[ 1.00943013, -1.00943013, -1.03561683, ..., -1.28024804,
        -1.16169394, -0.99419409],
       [-0.99065797,  0.99065797,  0.9656081 , ...,  0.06430269,
        -0.26087792, -0.17373982],
       [-0.99065797,  0.99065797,  0.9656081 , ..., -1.23950408,
        -0.36392329, -0.95964911],
       ...,
       [ 1.00943013, -1.00943013, -1.03561683, ..., -0.87280842,
        -1.17000405, -0.85451414],
       [-0.99065797,  0.99065797, -1.03561683, ..., -1.15801615,
         0.31916782, -0.87209546],
       [-0.99065797,  0.99065797,  0.9656081 , ...,  1.36810945,
         1.35793167,  2.01234407]], shape=(7032, 45))

#Separando o DF em treino e teste, para variáveis categoricas e classe e salvando em pickle para facilitar a utilização

In [55]:
X_treino,X_teste,y_treino,y_teste = train_test_split(X,y,test_size=0.2,random_state=42)

In [56]:
with open('data/data_churn_final.pkl','wb') as f:
    pickle.dump((X_treino,X_teste,y_treino,y_teste),f)